name: task
description: "A new Flutter project."

version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.4.1
  fl_chart: ^0.69.0
  cloud_firestore: ^5.4.1
  provider: ^6.1.2
  firebase_auth: ^5.3.0
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
